### ISSUE TITLE
Error: ProgressHttpModule is not an NgModule

### ISSUE THREAD

**Issue by alcfeoh** [DarkXaHTeP/angular-progress-http#1]
I'm getting this error while trying to use ProgressHttpModule. Any ideas on why it happens?

**Comment by DarkXaHTeP** [comment]
@alcfeoh could you please tell more about your environment (e.g. Angular version, build tools etc.)? It will help me understand the issue.

**Comment by alcfeoh** [comment]
I'm using Angular CLI with the following versions:

"dependencies": {
    "@angular/common": "^2.4.6",
    "@angular/compiler": "^2.4.6",
    "@angular/core": "^2.4.6",
    "@angular/forms": "^2.4.6",
    "@angular/http": "^2.4.6",
    "@angular/platform-browser": "^2.4.6",
    "@angular/platform-browser-dynamic": "^2.4.6",
    "@angular/router": "^3.4.6",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.20",
    "@ng-idle/core": "2.0.0-beta.4",
    "@ng-idle/keepalive": "2.0.0-beta.4",
    "@types/gapi": "0.0.30",
    "@types/gapi.auth2": "0.0.32",
    "@types/node": "^6.0.63",
    "angular-cli": "^1.0.0-beta.22-1",
    "angular-progress-http": "^0.2.2",
    "angular2-infinite-scroll": "^0.2.9",
    "angular2-moment": "^1.0.0",
    "angular2-uuid": "^1.1.1",
    "bootstrap": "^4.0.0-alpha.5",
    "codelyzer": "^2.0.0",
    "core-js": "^2.4.1",
    "epubjs": "^0.2.15",
    "hammerjs": "^2.0.8",
    "http-proxy": "^1.16.2",
    "jquery": "^3.1.1",
    "js-sha256": "^0.3.2",
    "karma-remap-istanbul": "^0.2.2",
    "moment": "^2.17.1",
    "ng2-infinite-scroll": "0.0.0",
    "ng2-nouislider": "^1.5.0",
    "ng2-translate": "^4.2.0",
    "nouislider": "^9.2.0",
    "rxjs": "5.0.0-rc.5",
    "ts-helpers": "^1.1.1",
    "unibabel": "^2.1.3",
    "zone.js": "^0.7.6"
  },
  "devDependencies": {
    "@angular/compiler-cli": "2.4.0",
    "@types/hammerjs": "^2.0.34",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "^1.0.0-beta.24",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.7.0",
    "karma": "1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.11",
    "ts-node": "1.7.0",
    "tslint": "4.0.2",
    "typescript": "2.0.10",
    "webdriver-manager": "10.2.10"
  }

**Comment by DarkXaHTeP** [comment]
@alcfeoh thanks, it seems that this kind of issue happens due to conflicts between typescript and angular-cli versions. Angular cannot read the metadata written by TypeScript compiler. I will take a look at it today in the evening and try to reproduce

**Comment by alcfeoh** [comment]
Thanks a lot for your quick answer. Perhaps you could include the actual TypeScript code instead of providing the compiled JS in your package? I could find a .d.ts file but not the actual .ts file in your npm module.

**Comment by DarkXaHTeP** [comment]
@alcfeoh, I replaced .js files with .ts as you suggested - this is the only thing that helped me resolve errors with compilation in Angular CLI. Could you please try 0.3.0 and say if the problem is resolved? I will close the issue if everything will be ok. Thanks!

**Comment by alcfeoh** [comment]
Thanks a lot for your quick answer. Will give it a try and let you know how it goes.

**Comment by alcfeoh** [comment]
Thanks, this works!

**Comment by neoassyrian** [comment]
Hi guys, 
I'm getting index.js is missing when I build it using VisualStudio. 

Can you perhaps include the index.js and the index.ts

**Comment by DarkXaHTeP** [comment]
@neoassyrian what build system do you use?

**Comment by DarkXaHTeP** [comment]
@neoassyrian please describe details as a new issue

**Comment by doender** [comment]
I think I've got the same problem. 
When using Ionic 3, I get:

```
Error: Uncaught Error: Module build failed: 
Error: ENOENT: no such file or directory, open 
'node_modules/angular-progress-http/index.js'
```

**Comment by DarkXaHTeP** [comment]
@doender please describe it as a new issue. It would be also great to have a link to an example where I could reproduce problem and fix for it. I have a plan to bring .js files back in 0.5.0 but need some time to set up a build with ngc, probably will release it somewhere on weekend

**Comment by hoorncj-student** [comment]
I opened a new issue before reading this. Let me know if I should restate the question in a way that aligns with the work you're doing.

**Comment by DarkXaHTeP** [comment]
@hoorncj thanks for opening. Issue #5 looks fine, I will comment there after releasing 0.5.0
