### ISSUE TITLE
How to use angular-progress-http in service

### ISSUE THREAD

**Issue by danyyacoub** [DarkXaHTeP/angular-progress-http#12]
This is a question rather than an issue,but i already have all my http requests in services, how can i migrate to angular-progress-http while keeping it in service ? 

Thanks

**Comment by DarkXaHTeP** [comment]
@danyyacoub on my current project I usually pass progress callback as an additional argument to service method and then return this.progressHttp.withUploadProgressListener(listenerFromArgument).get(url), which means that service signature stays almost the same e.g. getData(id, progressListener): Observable<Data>. Unfortunately I'm not able to provide code examples at the moment (vacation)

**Comment by danyyacoub** [comment]
Thanks, I got the idea.
Enjoy your vacation :)
