### ISSUE TITLE
possible incompatibility with the last version of angular

### ISSUE THREAD

**Issue by bogomips** [DarkXaHTeP/angular-progress-http#14]
I am not sure yet, since I've modified some code on my side.
It seems that after I upgraded  to    ` "@angular/http": "4.1.2"` it stopped working.
I'll check better, in the meanwhile does someone have the same issue?

**Comment by DarkXaHTeP** [comment]
@bogomips thanks for pointing it out! I will test library with 4.1.2 in a few hours and let you know

**Comment by DarkXaHTeP** [comment]
@bogomips Just checked how everything works with the latest angular version (4.1.3) and it seems to work as expected. Please create a separate issue if you have any questions regarding usage of the library

**Comment by bogomips** [comment]
Thanks, by digging a bit I discovered that the problem was caused by my usage of method apply() that I needed to dynamically set some parameters.
I refactored it in favor of the request() method plus  RequestOptions() now everything works fine.

A question for you:
Is it possible to configure how often the progress event is propagated? it seems like the lib throttles it

**Comment by DarkXaHTeP** [comment]
@bogomips there is a throttling in XmlHttpRequest itself. Unfortunately, there is nothing I can do about it

**Comment by bogomips** [comment]
Thank you so much for your answer
