### ISSUE TITLE
Replace deprecated OpaqueToken with InjectionToken<?>

### ISSUE THREAD

**Issue by michaelsanford** [DarkXaHTeP/angular-progress-http#15]
`OpaqueToken` is deprecated as of angular/core 4.0.0:

```typescript
/*
 * @deprecated since v4.0.0 because it does not support type information, use `InjectionToken<?>`
 * instead.
 */
export declare class OpaqueToken {
    protected _desc: string;
    constructor(_desc: string);
    toString(): string;
}
```

It should be replaced by typed `InjectionToken<?>`:

```typescript
/**
 * Creates a token that can be used in a DI Provider.
 *
 * Use an `InjectionToken` whenever the type you are injecting is not reified (does not have a
 * runtime representation) such as when injecting an interface, callable type, array or
 * parametrized type.
 *
 * `InjectionToken` is parameterized on `T` which is the type of object which will be returned by
 * the `Injector`. This provides additional level of type safety.
 *
 * ```
 * interface MyInterface {...}
 * var myInterface = injector.get(new InjectionToken<MyInterface>('SomeToken'));
 * // myInterface is inferred to be MyInterface.
 * ```
 *
 * ### Example
 *
 * {@example core/di/ts/injector_spec.ts region='InjectionToken'}
 *
 * @stable
 */
export declare class InjectionToken<T> extends OpaqueToken {
    private _differentiate_from_OpaqueToken_structurally;
    constructor(desc: string);
    toString(): string;
}
```

Doc: https://angular.io/api/core/InjectionToken

Discussion: https://stackoverflow.com/questions/43419050/angular-2-opaquetoken-vs-angular-4-injectiontoken

**Comment by michaelsanford** [comment]
Closing for now, as discussed in #16:

> Some developers, including my company, still have reasons to use Angular 2.x.x and I want to keep compatibility with it. Planning to change code to use InjectionToken only after release of Angular 5.x where OpaqueToken will be removed

**Comment by ChristofDC** [comment]
If you build an angular 4 project with --prod, it breaks functionality using OpaqueToken. Would it be possible to publish the latest version to npm or can I add a dependency to a different version which contains this modification?
Thanks!

**Comment by DarkXaHTeP** [comment]
@ChristofDC could you please provide more info about your issue? Right now an example project is built in prod mode with Angular 4+ and there are no problems

**Comment by ChristofDC** [comment]
If I just use ng serve everything works just fine, but when I use ng serve --prod it doesn't.
`return this.http
      .withUploadProgressListener(progress => {
        console.log(progress.percentage);
        this.requestProgress.emit(progress);
      })
      .post(url, body)
      .map(response => response.json());`

The console.log is not triggered but the post still happens.
I also don't get any error messages in console.

edit: I thought it was because of the OpaqueToken because I had similar behaviour on something else that was using OpaqueToken and when changing it to InjectionToken, that issue was resolved. But I've just changed your code to InjectionToken and the issue still persists so I was wrong

**Comment by DarkXaHTeP** [comment]
@ChristofDC I'm not sure that this issue has something to do with OpaqueToken.

Could you please describe it separately and say there next things
a) try your code in Chrome, Firefox, Edge and say if it works in any of them
b) were you able to run example project from the repo? did it work for you?
c) concrete versions of Angular and Angular CLI that you used in your app
d) any warnings or errors that you get during the build and run

Thanks!

**Comment by dmcclureagl** [comment]
This should be re-opened as it's now an issue with Angular 5.

There was an argument above about using angular2 and this, this is the reason why npm exists just use an older version if you're stuck on angular2.

**Comment by DarkXaHTeP** [comment]
@dmcclureagl agree, will publish a version with InjectionToken in a day or two

**Comment by DarkXaHTeP** [comment]
`OpaqueToken` is now replaced with `InjectionToken` and Angular 5.x.x is allowed in peerDependencies. See v0.6.0 on npm
