### ISSUE TITLE
Breaking changes in typescript 2.4.1

### ISSUE THREAD

**Issue by lvanderbijl** [DarkXaHTeP/angular-progress-http#17]
I'm getting the following error using the latest typescript - 2.4.1. Reverting to 2.3.2 fixed the issue 
```
ERROR in C:/git/admin-veronica-ng/node_modules/angular-progress-http/lib/AngularHttpFactory.d.ts (3,22): Class 'AngularHttpFactory' incorrectly implements interface 'HttpFactory'.
  Types of property 'create' are incompatible.
    Type '(backend: ConnectionBackend, requestOptions: RequestOptions) => Http' is not assignable to type '<T extends Http>(backend: ConnectionBackend, requestOptions: RequestOptions)
 => T'.
      Type 'Http' is not assignable to type 'T'.

```

**Comment by DarkXaHTeP** [comment]
Thank for reporting it! I'll take a look at this issue and let you know after fixing

**Comment by DarkXaHTeP** [comment]
@lvanderbijl I've deployed a new version 0.5.1 that contains a fix for the TypeScript breaking change. Could you please try it out? I'll reopen this issue if you'll still have the problem
