### ISSUE TITLE
browser inconsistency when using --prod

### ISSUE THREAD

**Issue by ChristofDC** [DarkXaHTeP/angular-progress-http#18]
Everything works when using ng serve, but when I use ng serve --prod there is inconsistent behaviour among different browsers. I do not get any errors or warning in the compiler or console.

Also I could not get the example project working out of the box because I got the following error:
```
ERROR in Error encountered resolving symbol values statically. Could not resolve angular-progress-http relative to C:/Users/chris/OneDrive/DEVtalk/Projects/Angular/angular-progress/examples/upload-download/src/app/app.module.ts., resolving symbol AppModule in C:/Users/chris/OneDrive/DEVtalk/Projects/Angular/angular-progress/examples/upload-download/src/app/app.module.ts, resolving symbol AppModule in C:/Users/chris/OneDrive/DEVtalk/Projects/Angular/angular-progress/examples/upload-download/src/app/app.module.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Users\chris\OneDrive\DEVtalk\Projects\Angular\angular-progress\examples\upload-download\src'
 @ ./src/main.ts 4:0-74
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
```

My angular versions:
```
@angular/cli: 1.0.0
node: 6.9.5
os: win32 x64
@angular/animations: 4.2.5
@angular/common: 4.2.5
@angular/compiler: 4.2.5
@angular/core: 4.2.5
@angular/forms: 4.2.5
@angular/http: 4.2.5
@angular/material: 2.0.0-beta.7
@angular/platform-browser: 4.2.5
@angular/platform-browser-dynamic: 4.2.5
@angular/router: 4.2.5
@angular/service-worker: 1.0.0-beta.16
@angular/cli: 1.0.0
@angular/compiler-cli: 4.2.5
```
My code:
```
return this.http
      .withUploadProgressListener(progress => {
        console.log(progress.percentage);
        this.requestProgress.emit(progress)
      })
      .post(url, body)
      .map(response => response.json());
```
Browser behaviour:
IE => OK, in console I get an incremental percentage
Edge => NOK, in console I don't get an incremental percentage, only 100 at the end of the upload.
Chrome => NOK, I don't get anything in console
Firefox => NOK, I don't get anything in console

**Comment by DarkXaHTeP** [comment]
@ChristofDC did you build a library from sources before running examples, as described [here](https://github.com/DarkXaHTeP/angular-progress-http#running-examples)?

**Comment by DarkXaHTeP** [comment]
@ChristofDC one more thing: when building library from sources make sure that you use typescript < 2.4 (it will install 2.4.1 by default). There are some breaking changes in type checking, as described in #17 . I'm already working on fix for it, sorry for inconvenience.

**Comment by ChristofDC** [comment]
For my own project or the example project?
I don't need to build when I use npm install angular-progress-http, right?
In my own project I'm using typescript 2.2.2... I think (package.json > typescript 2.2.2)?

**Comment by DarkXaHTeP** [comment]
@ChristofDC for example project. npm package comes pre-compiled

**Comment by ChristofDC** [comment]
I am getting the error for typescript you defined. How can I change typescript to be < 2.4?

**Comment by DarkXaHTeP** [comment]
a few options here

- update package.json after you checkout a repo `"typescript": "~2.3.0",` and run `npm install`
- run "npm install typescript@2.3"
- just give it a break for a few hours while I fix typescript issue and I'll let you know when it's done

**Comment by ChristofDC** [comment]
I just noticed that it is only on my machine that this does not work so probably just a local problem.
So this is not an issue anymore regarding your code.
Thanks for the quick responses!

**Comment by DarkXaHTeP** [comment]
@ChristofDC you're welcome
