### ISSUE TITLE
Getting an error while running the build

### ISSUE THREAD

**Issue by siva2sachin** [DarkXaHTeP/angular-progress-http#2]
While running npm run build, getting below error,
Could you please help me to understand the issue?

> angular-progress-http@0.3.0 copy-ts C:\Siva\Devlopment\angular-progress-http
> copyup 'src/**/*' build

> angular-progress-http@0.3.0 transform-package C:\Siva\Devlopment\angular-prog
ess-http
> node scripts/transformPackageJson.js

fs.js:558
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Siva\Devlopment\angular-prog
ess-http\build\package.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.writeFileSync (fs.js:1223:33)
    at Object.<anonymous> (C:\Siva\Devlopment\angular-progress-http\scripts\tra
sformPackageJson.js:11:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by DarkXaHTeP** [comment]
@siva2sachin It is a very strange thing. Looks like "build" directory is not yet created when build script writes transformed package.json to it. I added some checks into the transformPackageJson script and create build folder if it doesn't exist now. Could you please try the latest sources in master branch and say if it helps?

**Comment by siva2sachin** [comment]
Thanks, @DarkXaHTeP . It worked. But however When I run npm run examples command, I'm getting below error,
Could you please help me on this.

[at-loader] Checking started in a separate process...

[at-loader] Checking finished with 4 errors
Hash: c1e461b49a9f756db199
Version: webpack 1.14.0
Time: 9994ms
        Asset     Size  Chunks             Chunk Names
    bundle.js  2.27 MB       0  [emitted]  bundle
bundle.js.map  2.74 MB       0  [emitted]  bundle
    + 29 hidden modules

ERROR in ./app/app.module.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build in
C:\Siva\Devlopment\New folder\angular-progress-http\examples/src\app
 @ ./app/app.module.ts 12:14-39

ERROR in ./app/app.component.ts
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../build in
C:\Siva\Devlopment\New folder\angular-progress-http\examples/src\app
 @ ./app/app.component.ts 13:14-39


ERROR in [at-loader] examples\src\app\app.component.ts:2:30
    TS2307: Cannot find module '../../../build'.

ERROR in [at-loader] examples\src\app\app.component.ts:55:45
    TS7006: Parameter 'progress' implicitly has an 'any' type.

ERROR in [at-loader] examples\src\app\app.component.ts:57:29
    TS7006: Parameter 'r' implicitly has an 'any' type.

ERROR in [at-loader] examples\src\app\app.module.ts:4:36
    TS2307: Cannot find module '../../../build'.

**Comment by DarkXaHTeP** [comment]
@siva2sachin my bad, I did not check how the library build behaves on Windows because my primary OSs are Linux and macOs. However now I did that check and fixed a few more issues in package.json and webpack config. Please try running `npm run build` and `npm run examples` with the newest sources

**Comment by siva2sachin** [comment]
Thanks @DarkXaHTeP . It worked well.

**Comment by siva2sachin** [comment]
@DarkXaHTeP  It's working very nicely. However I uploaded the files, the uploading is successful as like below,

Example app listening on port 3000!
Uploaded file Desert.jpg
Uploaded file Lighthouse.jpg
Uploaded file Tulips.jpg
Uploaded file Koala.jpg
Uploaded file Penguins.jpg

Now my question is, I see upload location is \fileupload. Is that a local folder location or posting to a servlet method. I'm just learning with your program. Thanks for your help.

**Comment by DarkXaHTeP** [comment]
@siva2sachin the example contains a simple Express server that receives files from Angular app. This server does nothing with files except printing their names to console. See server sources [in this file](https://github.com/DarkXaHTeP/angular-progress-http/blob/master/examples/server.js)

**Comment by DarkXaHTeP** [comment]
Closing the issue since the build works on Windows
