### ISSUE TITLE
Angular 5 compatibility

### ISSUE THREAD

**Issue by adrianwilson** [DarkXaHTeP/angular-progress-http#21]
Any plans for Angular 5 compatibility? We'll be forking this locally in our project. Would be happy to contribute if needed.

**Comment by DarkXaHTeP** [comment]
@adrianwilson starting from Angular 4.3.0 there is a new way to interact with server instead of Http - HttpClient. It supports Progress events out of the box, so I don't see any real need to update this library. Check it out here - https://angular.io/guide/http#listening-to-progress-events

**Comment by adrianwilson** [comment]
This is great, thanks!

**Comment by DarkXaHTeP** [comment]
@adrianwilson you are welcome
