### ISSUE TITLE
Hello, can the upload mode be changed to sync? Thanks!

### ISSUE THREAD

**Issue by Evllis** [DarkXaHTeP/angular-progress-http#29]
Now the upload mode is asynchronous. I want to change it into synchronous mode and upload one by one. Is that ok?

**Comment by DarkXaHTeP** [comment]
@Evllis unfortunately, it is not possible to make synchronous requests with Angular Http, however you could take advantage of `rxjs` library to upload files one by one. Please find example below:
```ts
function uploadFile(file: File): Observable<void> {
  const form = new FormData();
  form.append("file", file);
  return progressHttp
    .withUploadProgressListener(progress => { console.log(`Uploading ${progress.percentage}%`); })
    .post("/fileUpload", form)
    .do(() => { console.log(file.name + " uploaded"); });
}

function uploadOneByOne(files: File[]): Observable<void> {
  return files.reduce((observable, file) => {
    return observable.switchMap(() => uploadFile(file))
  }, emptyObservable);
}

// usage
uploadOneByOne(someFiles)
  .subscribe(() => console.log("All uploaded"));
```
Please note that I did not test the code above

**Comment by Evllis** [comment]
Thank you very much.

I used async and wait to synchronize the operation.

**Comment by Evllis** [comment]
@DarkXaHTeP 
Thank you very much.

I used async and wait to synchronize the operation.
