### ISSUE TITLE
Existing RxJs Import are invalid for angular 6

### ISSUE THREAD

**Issue by avinash-wissen** [DarkXaHTeP/angular-progress-http#30]

**Comment by fromage9747** [comment]
some more detail as avinash-wissen hasn't provided any.
When trying to run: ng update @angular/cli @angular/core, the below is received:
`Package "angular-progress-http" has an incompatible peer dependency to "@angular/core" (requires "^4.0.0 || ^5.0.0" (extended), would install "7.0.4").
                  Package "angular-progress-http" has an incompatible peer dependency to "@angular/http" (requires "^4.0.0 || ^5.0.0" (extended), would install "7.0.4").
Package "angular-progress-http" has an incompatible peer dependency to "rxjs" (requires "^5.0.1", would install "6.3.3").`

**Comment by DarkXaHTeP** [comment]
@avinash-wissen there is no need to use this library with Angular 6+. Check out the official documentation for a new HttpClient [here](https://angular.io/guide/http#listening-to-progress-events)
