### ISSUE TITLE
 I have an error with the implementation in an angular 5

### ISSUE THREAD

**Issue by briancaldas93** [DarkXaHTeP/angular-progress-http#31]
![image](https://user-images.githubusercontent.com/16884130/63061784-fe880680-bebb-11e9-8b97-6b386943d420.png)

**Comment by DarkXaHTeP** [comment]
Hi @briancaldass, please make sure that both HttpModule from @angular/http and ProgressHttpModule are imported. Also note that if you are using Angular 4.3.0 and later, I would suggest migrating to @angular/common/http that supports progress events out of the box.

**Comment by briancaldass** [comment]
I have ProgressHttpModule imported correctly and I have the angular HttpClientModule since I am using angular version 5.2 everything is fine

![image](https://user-images.githubusercontent.com/16884130/63189558-e0401900-c029-11e9-968c-add19001ded2.png)

**Comment by briancaldas93** [comment]
> Hola @briancaldass , asegúrese de que se importen tanto HttpModule de @ angular / http como ProgressHttpModule. También tenga en cuenta que si está utilizando Angular 4.3.0 y posterior, sugeriría migrar a @ angular / common / http que admita eventos de progreso listos para usar.

I have ProgressHttpModule imported correctly and I have the angular HttpClientModule since I am using angular version 5.2 everything is fine

![image](https://user-images.githubusercontent.com/16884130/63189683-24cbb480-c02a-11e9-848e-23c0f92ad41d.png)

**Comment by DarkXaHTeP** [comment]
@briancaldass you don’t need the library if you use HttpClient already. Also HttpModule from @angular/http is not same as HttpClientModule from @angular/common/http

**Comment by briancaldas93** [comment]
> @briancaldass you don’t need the library if you use HttpClient already. Also HttpModule from @angular/http is not same as HttpClientModule from @angular/common/http

Ok I understand that part of the implementation now I get an error in the headers

![image](https://user-images.githubusercontent.com/16884130/63192870-b559c300-c031-11e9-9bc8-ac174a5581a7.png)

My code in the headers it is

![image](https://user-images.githubusercontent.com/16884130/63192896-c73b6600-c031-11e9-8bac-d82ab30ce545.png)

**Comment by DarkXaHTeP** [comment]
@briancaldass I guess the error message is very detailed. Please either use @angular/http and angular-progress-http everywhere, or replace both of them with @angular/common/http (recommended since @angular/http is deprecated and removed completely starting from Angular 6). Do not mix up imports from one (HttpHeaders is from @angular/common/http) with another - it will not work and the library has nothing to do with it
