### ISSUE TITLE
node module should be pre-compiled

### ISSUE THREAD

**Issue by hoorncj-student** [DarkXaHTeP/angular-progress-http#5]
It is common when developing with Typescript + NPM to ignore node_modules folder when compiling. By requiring your module to be compiled, we are forced to either enumerate all modules in the tsconfig that shouldn't be compiled or compile all of our node_modules, neither of which are particularly friendly. It would be preferable to include an index.js either instead of index.ts or additionally in a dist/ folder and refer to it from package.json.

**Comment by DarkXaHTeP** [comment]
@hoorncj @neoassyrian @doender I've brought back .js files in 0.5.0. It is already published to npm. Could you please check and say if everything works with new version?

**Comment by hoorncj-student** [comment]
What is your recommendation for accessing the Progress interface? It seems to have been removed from index.

**Comment by DarkXaHTeP** [comment]
@hoorncj it is still there, take a look at index.d.ts. This is how interfaces are compiled in TypeScript

**Comment by DarkXaHTeP** [comment]
Closing it since no new comments were added to the issue. Assuming that everything works as expected
